;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sparkfun_promicro16]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino

upload_protocol = avr109
; each flag in a new line
upload_flags =
    -P$UPLOAD_PORT
    -b$UPLOAD_SPEED
    -D
; edit these lines
;upload_port = COM3
;upload_speed = 115200
;upload_port = /dev/ttyButton
;board_upload.use_1200bps_touch = false
;board_upload.wait_for_upload_port = false  